### ISSUE TITLE
Phase 1 Tracking

### ISSUE THREAD

**Issue by hugomrdias** [ipfs-examples/js-ipfs-examples#15]
# Tracking for  Phase 1 Multirepo-ization

- [x] CI setup to pull examples from remote source repos (https://github.com/ipfs-examples/ipfs-101)
- [x] Check if exist changes when pulling examples to avoid unnecessary commits
- [x] Add all the js-ipfs examples
- [x] Proper setup for the ipfs-examples organisation (ask andy)
- [x] Turn off issue/wikis/projects/discussions for all examples
- [x] Add descriptions in each example
- [x] Add website pointing back to the original source
- PR template linking to the main repo (https://github.com/ipfs-examples/example-fork-go-template/pull/1)
- Readme files are going to be updated in Phase 2 linking to main repo using a template
- [x] Disable Releases/Environments/Packages in each example 
<img width="1161" alt="Screenshot 2021-06-10 at 10 31 54" src="https://user-images.githubusercontent.com/314190/121501368-160c7980-c9d7-11eb-9fb5-513464a60d0b.png">
