### ISSUE TITLE
Phase 3 Tracking

### ISSUE THREAD

**Issue by oliveriosousa** [ipfs-examples/js-ipfs-examples#30]
# Tracking for Phase 3 - Make remotely runnable

Example repos each have Glitch.com and Codesandbox.com projects for one-click running
The one-click run locations are automatically updated when the repo example is updated

### Fix codesandbox/stackblitz problems

- https://github.com/ipfs/js-ipfs-utils/pull/136
- https://github.com/achingbrain/native-fetch/pull/3

**Comment by oliveriosousa** [comment]
## Summary

- `browser-add-readable-stream`

  - [ ] Runs without issues
  - [ ] Runs with issues
  - [x] Fails
    - Could not fetch https://data.jsdelivr.com/v1/package/npm/node-fetch@2.6.7/flat
    - ModuleNotFoundError: Could not find module in path: 'xmlhttprequest-ssl' relative to '/node_modules/engine.io-client/lib/transports/index.js)
  
- `browser-angular`

  - [ ] Runs without issues
  - [ ] Runs with issues
  - [x] Fails
    - Could not fetch https://data.jsdelivr.com/v1/package/npm/node-fetch@2.6.7/flat
    - TypeError: asn.define is not a function (node_modules/parse-asn1/certificate.js:8:16)

**Comment by oliveriosousa** [comment]
Currently, `codesandbox` is throwing the following error: 

`ModuleNotFoundError: Could not find module in path: 'xmlhttprequest-ssl' relative to '/node_modules/engine.io-client/lib/transports/index.js)`

### Temporary solution (until is fixed)

- Fork the example (using codesandbox)
- Import `socket.io-client` and downgrade to version `4.1.3`
